# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x191724ff
bordercolor = 0x656278ff
dropcolor = 0xebbcba80
splitcolor = 0x31748fff
focuscolor = 0xebbcbaff
maximizescreencolor = 0x9ccfd8ff
urgentcolor = 0xeb6f92ff
scratchpadcolor = 0x31748fff
globalcolor = 0xc4342eff
overlaycolor = 0x2e8493ff
jump_label_decorate_fg_color = 0xe0def4ff
jump_label_decorate_bg_color = 0x2e2b47ff
jump_label_decorate_focus_fg_color = 0x191724ff
jump_label_decorate_focus_bg_color = 0xebbcbaff
jump_label_decorate_border_color = 0x656278ff
group_bar_decorate_fg_color = 0xe0def4ff
group_bar_decorate_bg_color = 0x2e2b47ff
group_bar_decorate_focus_fg_color = 0x191724ff
group_bar_decorate_focus_bg_color = 0xebbcbaff
group_bar_decorate_border_color = 0x656278ff
